Use githubs gitignore files.
kit-data-manager/template pull request #5
Opened 2021-09-28 11:28 UTC by Pfeil

I'd prefer to use this kind of gitignore file. It uses some of the well-maintained lists from https://github.com/github/gitignore. This makes basically two changes:

- Include a lot of files we have never seen and usually will not see.
- Exclude all folders named "build" by default, with the exceptions of such folders located in `/src`. If a legit exception has to be added, it can be done like this: `!/setup/build/env.sh` but to be honest I do not expect this to happen.

I left in some things I was not able to tell where it is coming from, namely `/.settings/` and `/config/`, so no lines or files were left out in the end.

2021-09-29 06:11 UTC, VolkerHartmann commented on .gitignore
> -**/application.properties
I miss the following line in the new file. 
This should be also part of .gitignore as application.properties may contain private information.
(e.g. password for database, ...)
###  SPRING BOOT ###
# Ignore local settings for spring boot
# If you want to provide default settings use 'application.properties.default' and rename it while building service.
**/application.properties
##############

2021-11-16 12:02 UTC, Pfeil commented
Sorry for the force push, I thought I did not have a pull request already. But well.

- modified the starting comment a little to make it hopefully a little better to understand what I mean.
- Added os specific files to avoid thumbnails and similar things to be committed.
- Added the line you proposed.

What do you think?

2021-11-16 16:45 UTC, Pfeil commented
If this is fine, I think you'll have to merge, I think I can not ... probably that is why I forked the template repo back then :)

2021-11-24 14:47 UTC, Pfeil commented
Merging the master has deleted the travis.yaml, still it seems to be triggered? The rest of the CI is probably fixed by #6 by then.

2021-11-30 06:36 UTC, VolkerHartmann requested changes

2021-11-30 06:36 UTC, VolkerHartmann commented on .gitignore
> +!gradle-wrapper.jar
Works not for me!?
!gradle/wrapper/gradle-wrapper.jar may be better.

2021-11-30 06:39 UTC, VolkerHartmann commented on .gitignore
> +!gradle-wrapper.jar
Alternatively to make it more flexible:
!**/gradle-wrapper.jar

2021-11-30 10:55 UTC, Pfeil commented on .gitignore
> +!gradle-wrapper.jar
Whoops, thanks. Should be fixed now.

2022-07-12 05:42 UTC, VolkerHartmann commented on .gitignore
> +##############
New line missing at the end!

2022-07-13 13:23 UTC, Pfeil commented on .gitignore
> +##############
Done :)

2022-07-15 14:02 UTC, merged