Add github ci.
kit-data-manager/template pull request #7
Opened 2021-11-23 11:13 UTC by Pfeil

- should we remove the travis.yml?
- what has to be done for $code_coverage_dashboard?

2021-11-23 12:11 UTC, ThomasJejkal commented
Point 1:  yes
Point 2:  Doesn't the [metastore2 configuration](https://github.com/kit-data-manager/metastore2/blob/master/.github/workflows/gradle.yml) helps on this?

2021-11-24 07:56 UTC, Pfeil commented
Point 1: Done
Point2: Well yes and no. Metastore (and other projects, too) also have a gradle dependency to a coveralls library, and I am not sure yet what the official way is etc.

2021-11-24 08:40 UTC, ThomasJejkal commented
Well, I think you need the dependency anyways. Which alternative do you see?

2021-11-24 09:40 UTC, Pfeil commented
I think the dependency is not used by the CI, is it? Maybe I just do not understand how it works. I also just noticed that the metastore config uses codecov and I am talking about the coveralls dependency. Do we have a decision on what to use?

2021-11-24 10:47 UTC, Pfeil commented
I added the codecov CI workflow. Can be merged now. I will remove the coveralls dependency in the gradle file in #6 .

2021-11-24 12:31 UTC, VolkerHartmann requested changes
See comment...

2021-11-24 12:31 UTC, VolkerHartmann commented on .github/workflows/gradle.yml
> +        java-version: ${{ env.currentBuildVersion }}
You have to define this environment variable at the top of this file.

2021-11-24 13:53 UTC, Pfeil commented on .github/workflows/gradle.yml
> +        java-version: ${{ env.currentBuildVersion }}
Whoops. Done. I renamed it a little so it is hopefully clear what part it influences.

2021-11-24 14:20 UTC, VolkerHartmann approved these changes
Well done!

2021-11-24 14:22 UTC, merged